//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        public int userID { get; set; }
        [DisplayName("username")]
        [Required(ErrorMessage = "The field is rerquired.")]

        public string UserName { get; set; }
        [DataType("password")]
        [Required(ErrorMessage = "The field is rerquired.")]

        public string password { get; set; }
        public string Email { get; set; }
        [DisplayName("Encrypted password")]
        public string Salt { get; set; }
        public string LoginErrorMessage { get; internal set; }
    }
}
