//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rental()
        {
            this.Invoices = new HashSet<Invoice>();
            this.Junctions = new HashSet<Junction>();
        }
    
        public int rentalID { get; set; }
        public Nullable<System.DateTime> receiveDate { get; set; }
        public Nullable<System.TimeSpan> receiveHr { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
        public Nullable<System.TimeSpan> returnHr { get; set; }
        public bool buyRent { get; set; }
        public string receiveDoc { get; set; }
        public string returnDoc { get; set; }
        public Nullable<int> rentalRate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Junction> Junctions { get; set; }
    }
}
